config/routes.rb
Rails.application.routes.draw do
  resources :logs

  root 'logs#index'

end

app/models/log.rb
class Log < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
  before_action :set_log, only: [:show, :edit, :update, :destroy]

  # GET /logs
  # GET /logs.json
  def index
    @logs = Log.all
    @log = Log.new
  end

  # GET /logs/1
  # GET /logs/1.json
  def show
  end

  # GET /logs/new
  def new
    @log = Log.new
  end

  # GET /logs/1/edit
  def edit
  end

  # POST /logs
  # POST /logs.json
  def create
    @log = Log.new(log_params)

    respond_to do |format|
      if @log.save
        format.html { redirect_to logs_url, notice: 'Saved!' }
        format.json { render :show, status: :created, location: @log }
      else
        format.html { render :new }
        format.json { render json: @log.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /logs/1
  # PATCH/PUT /logs/1.json
  def update
    respond_to do |format|
      if @log.update(log_params)
        format.html { redirect_to @log, notice: 'Saved!' }
        format.json { render :show, status: :ok, location: @log }
      else
        format.html { render :edit }
        format.json { render json: @log.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /logs/1
  # DELETE /logs/1.json
  def destroy
    @log.destroy
    respond_to do |format|
      format.html { redirect_to logs_url, notice: 'Removed!' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_log
      @log = Log.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def log_params
      params.require(:log).permit(:food, :calories, :time)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Flog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src="https://use.typekit.net/lrb6oto.js"></script>
  <script>try{Typekit.load({ async: true });}catch(e){}</script>
</head>
<body class="body">

<%= yield %>

</body>
</html>

app/views/logs/_form.html.erb
<%= form_for(@log) do |f| %>
  <% if @log.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@log.errors.count, "error") %> prohibited this log from being saved:</h2>

      <ul>
      <% @log.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="text-area">
    <%= f.text_area :food, placeholder: "I just ate..." %>
  </div>
  <div class="form-field">
    <%= f.text_field :calories, placeholder: "Calories" %>
  </div>
  <div class="form-field last">
    <%= f.text_field :time, placeholder: "Time" %>
  </div>
  <div class="submit-btn">
    <%= f.submit "Save", :class => 'flog-btn' %>
  </div>
<% end %>

app/views/logs/edit.html.erb
<center>
  <%= image_tag("ico-logs.png", class: "logo") %>
</center>

<div class="back-btn">
  <%= link_to '', logs_path, class: "glyphicon glyphicon-remove" %>
</div>

<div class="container-fluid card">
  <div class="row form">
    <%= render 'form' %>
  </div>
</div>

<div class="text-center">
  <%= link_to 'Remove', @log, method: :delete, data: { confirm: 'Are you sure?' } %>
</div>

app/views/logs/index.html.erb
<span id="notice" class="notice"><%= notice %></span>
<center>
  <%= image_tag("ico-logs.png", class: "logo") %>
</center>

<div class="container-fluid card">
  <div class="row form">

    <%= render 'form' %>


  </div>
</div>

<div class="container-fluid card">

  <div class="row">
    <div class="pull-left card-header">

      <span class="header">Today</span><br>
      <span class="sub-header">Thursday, Jan 5, 2017</span>

    </div>

    <div class="pull-right calorie-total">

      <span class="cal-head">600</span><br>
      <span class="cal-sub">calories</span>

    </div>
  </div>

  <hr>

  <% @logs.each do |log| %>
    <div class="row list-item">

      <div class="pull-left">
        <span class="item-name"><%= link_to log.food, edit_log_path(log) %></span><br>
        <span class="sub-header"><%= log.time %></span>
      </div>

      <div class="pull-right">
        <span class="cal-head"></span>
      </div>

    </div>
  <% end %>

</div>

<div class="container-fluid card">

  <div class="row">
    <div class="pull-left card-header">

      <span class="header">Yesterday</span><br>
      <span class="sub-header">Thursday, Jan 4, 2017</span>

    </div>

    <div class="pull-right calorie-total">

      <span class="cal-head">600</span><br>
      <span class="cal-sub">calories</span>

    </div>

  </div>
</div>


      <!-- <% @logs.each do |log| %>
        <%= log.food %>
        <%= log.calories %>
        <%= log.time %>
        <%= link_to 'Show', log %>
        <%= link_to 'Edit', edit_log_path(log) %>
        <%= link_to 'Destroy', log, method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %> -->


<!-- <%= link_to 'New Log', new_log_path %> -->

app/views/logs/new.html.erb
<h1>New Log</h1>

<%= render 'form' %>

<%= link_to 'Back', logs_path %>

app/views/logs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Food:</strong>
  <%= @log.food %>
</p>

<p>
  <strong>Calories:</strong>
  <%= @log.calories %>
</p>

<p>
  <strong>Time:</strong>
  <%= @log.time %>
</p>

<%= link_to 'Edit', edit_log_path(@log) %> |
<%= link_to 'Back', logs_path %>